IA/Models/project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.feedbacks = new HashSet<feedback>();
            this.mangaed_projects = new HashSet<mangaed_projects>();
            this.project_comments = new HashSet<project_comments>();
            this.project_members = new HashSet<project_members>();
            this.requests = new HashSet<request>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int duration { get; set; }
        public int customer_id { get; set; }
        public int posting_state_id { get; set; }
        public int assigend_state_id { get; set; }
        public System.DateTime creation_date { get; set; }
    
        public virtual ICollection<feedback> feedbacks { get; set; }
        public virtual ICollection<mangaed_projects> mangaed_projects { get; set; }
        public virtual ICollection<project_comments> project_comments { get; set; }
        public virtual ICollection<project_members> project_members { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}

IA/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;


namespace Test.Controllers
{
	public class CustomerController : Controller
	{
        Database2Entities3 db = new Database2Entities3();

		//
		// GET: /Customer/
		public ActionResult Index()
		{
			return View();
		}



		public ActionResult CreateProject()
		{
			return View();
		}

        


		[HttpPost]
		public ActionResult CreateProject(project project)
		{

			project.assigend_state_id = 3;
			project.posting_state_id = 1;
            int id = Convert.ToInt32(Session["ID"]);
            project.customer_id = id;
            project.creation_date = DateTime.Now;
			db.projects.Add(project);
		

			db.SaveChanges();
			return  RedirectToAction("GetProjects");
		}
		public ActionResult GetProjects()
		{
            int id = Convert.ToInt32(Session["ID"]);
            return View(db.projects.Where(u =>  u.customer_id == id).ToList());
		}

		public ActionResult Edit(int? id)
		{

			return View(db.projects.Find(id));
		}
		[HttpPost]
		public ActionResult Edit(project project)
		{
			project result = (from p in db.projects
							 where p.Id == project.Id
							 select p).SingleOrDefault();
			result.description=project.description;
			result.duration=project.duration;
			result.title=project.title;

			db.SaveChanges();
			return RedirectToAction("GetProjects");
		}


		public ActionResult Remove(int ?id)
		{

			project project = db.projects.Find(id);

			if (project.assigend_state_id == 4)
			{
				return Content("Error !!, its already assigned to user !!");
			}
			else
			{
			
		   

				db.projects.Remove(project);
				db.SaveChanges();
				return RedirectToAction("GetProjects");

			}

			

		}



        public ActionResult Details(int? id)
        {

            return View(db.projects.Find(id));
        }

        public ActionResult get_projectmanger_request()
        {
            int id = Convert.ToInt32(Session["ID"]); 
            return View(db.requests.Where(u => u.reciever_id== id&& u.state_id==1).ToList());
        }

        public ActionResult Assign_pm(int id)
        {
            request result = (from p in db.requests
                              where p.Id == id
                              select p).SingleOrDefault();
            result.state_id = 4;
            mangaed_projects mp = new mangaed_projects();
            mp.pm_id = result.sender_id;
            mp.project_id = result.project_id;
            mp.state_id = 6;
            mp.start_date = DateTime.Now;
            mp.deliver_date = DateTime.Now;
            mp.cost = 5000;
            db.mangaed_projects.Add(mp);
            db.SaveChanges();
            return RedirectToAction("get_projectmanger_request");
        }
	}
}

IA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;


namespace IA.Controllers
{
    public class HomeController : Controller
    {
        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /Home/
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult projects()
        {
            return PartialView("projects",db.projects.ToList());
        }

        [HttpPost]
        public JsonResult List()
        {
            var states = db.user_type.Where(c => c.id != 1).ToList();
            List<SelectListItem> listates = new List<SelectListItem>();

            listates.Add(new SelectListItem { Text = "Select Type", Value = "0" });
            if (states != null)
            {
                foreach (var x in states)
                {
                    listates.Add(new SelectListItem { Text = x.name, Value = x.id.ToString() });

                }



            }


            return this.Json(new SelectList(listates, "Value", "Text", JsonRequestBehavior.AllowGet));
        }  
        
	}
}

IA/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;

namespace IA.Controllers
{
    public class UserController : Controller
    {
        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /User/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index2()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult login(user user)
        {
            user myUser = db.users.FirstOrDefault(u => u.email.Equals(user.email) && u.password.Equals(user.password));

            if (myUser != null)
            {
                //TempData["ID"] = myUser.id;
                Session["ID"] = myUser.id;
                Session["phone"] = myUser.phone_number;
                Session["name"] = myUser.fname + " " + myUser.lname;
                Session["usertype"] = myUser.type_id;
                Session["email"] = myUser.email;
                //Session["jobdesc"] = myUser.user_type.name;
                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewBag.message = "User name or password is not Valid";
                return RedirectToAction("Index", "Home");
            }
 
        }

        public ActionResult logout()
        {
            Session.Abandon();//DESTROY SESSION
            return RedirectToAction("index","Home");
        }


        public ActionResult register()
        {
            return View();
        }



        [HttpPost]
        public ActionResult register(user u)
        {
            if(u!=null)
            {
                Session["ID"] = u.id;
                Session["name"] = u.fname + " " + u.lname;
                Session["usertype"] = u.user_type;
                Session["email"] = u.email;
                db.users.Add(u);
                db.SaveChanges();
                login(u);
                return RedirectToAction("index","Home");
            }
            else
            {
                ViewBag.message = "please fill all filds";
                return View();
            }
            
        }
        
	}



}

IA/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Home.cshtml";
}

IA/Views/Home/Index2.cshtml
@model IEnumerable<IA.Models.project>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Home2.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.posting_state_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.assigend_state_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creation_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.user.lname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.posting_state_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.assigend_state_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creation_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.user.lname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

IA/Views/Home/Partial1.cshtml
@model IA.Models.project
           
@using (Html.BeginForm("CreateProject", "Customer"))

{
    
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Add Project</h2>
    
    @{
        if (Convert.ToInt32(HttpContext.Current.Session["usertype"]) == 4)
        {
        @Html.ValidationSummary(true)

        <div class="form-group">
           <label class = "col-md-2">Title</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.title, new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.title)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2">Description</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2">Duration</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.duration, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.duration)
            </div>
        </div>



        <div class="form-group">
            <div class="text-center col-md-12">
                <input type="submit" value="Create" class="btn btn-default submit " />
            </div>
        </div>
        }
        else
        {
                @Html.ValidationSummary(true)

        <div class="form-group">
           <label class="col-md-2">Title</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.title, new {disabled="disabled" , @class = "form-control" })

                @Html.ValidationMessageFor(model => model.title)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2">Description</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.description, new { disabled = "disabled", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2">Duration</label>
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.duration, new { disabled = "disabled", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.duration)
            </div>
        </div>



        <div class="form-group">
            <div class="text-center col-md-12">
                <input type="submit" value="Create" class="btn btn-default submit" disabled="disabled" />
            </div>
        </div>
            
        }
    }
    </div>
    

}

IA/Views/Home/login.cshtml
@model IA.Models.user
@using (Html.BeginForm("login", "User"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)



        <div class="form-group">
            <label class="col-md-12">Email</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.email, new { @class = "form-control ", Type = "Email" })
                @Html.ValidationMessageFor(model => model.email)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-12">Password</label>
            <div class="col-md-12">
                @Html.PasswordFor(model => model.password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.password)
            </div>
        </div>


        <div class="form-group">
            <div class="text-center col-md-12">
                <input type="submit" value="Login" class="btn btn-default submit" />

            </div>
        </div>
    </div>
}
@{Html.EndForm();}

IA/Views/Home/projects.cshtml
@model IEnumerable<IA.Models.project>

<p>
   
</p>
<table class="table main-table table-bordered text-center">
    <tr>
        <th>
            <div>
                Title
            </div>
            
        </th>
        <th>

            <div>
                Description
            </div>
        </th>
        <th>
            <div>
                Duration
            </div>
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.duration)
        </td>
        
    </tr>
}

</table>

IA/Views/Home/register.cshtml
@model IA.Models.user

@using (Html.BeginForm("register", "User"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <div class="form-group">
            <label class="col-md-12">First Name</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.fname, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fname)
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-12">Last Name</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.lname, new { @class = "form-control " })
                @Html.ValidationMessageFor(model => model.lname)
            </div>
        </div>



        <div class="form-group">
            <label class="col-md-12">Email</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.email, new { @class = "form-control", Type = "email" })
                @Html.ValidationMessageFor(model => model.email)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-12">Password</label>
            <div class="col-md-12">
                @Html.PasswordFor(model => model.password, new { @class = "form-control", Type = "password" })
                @Html.ValidationMessageFor(model => model.password)
            </div>
        </div>

        <div class="form-group text-left">
            <label class="col-md-12">Mobile</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.phone_number, new { @class = "form-control " })
                @Html.ValidationMessageFor(model => model.phone_number)
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-12">Job Description</label>
            <div class="col-md-12">
                @Html.TextAreaFor(model => model.jop_description, new { @class = "form-control " })
                @Html.ValidationMessageFor(model => model.jop_description)
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-12">Type Id</label>
            <div class="col-md-12">
                @Html.TextBoxFor(model => model.type_id, new { @class = "text-left form-control", Type = "id" })
            </div>
        </div>


        <div class="form-group">
            <label class="col-md-12">Photo</label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.image)
                @Html.ValidationMessageFor(model => model.image)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-12 text-center">
                <input type="submit" value="Create" class="btn btn-default submit" />
            </div>
        </div>
    </div>
}
@{Html.EndForm();}