IA/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using IA.Models;
namespace IA.Controllers
{
    public class AdminController : Controller
    {
        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /Admin/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult manageusers()
        {
            return View(db.users.ToList());
        }

        public ActionResult details()
        {

            return View(db.users.Find(1));
        }

        public ActionResult Deleteuser(int id)
        {
            user p = db.users.Find(id);
            db.users.Remove(p);
            db.SaveChanges();
            return RedirectToAction("manageusers");
        }

        public ActionResult Adduser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Adduser(user u)
        {
            db.users.Add(u);
            db.SaveChanges();
            return RedirectToAction("manageusers");
        }

        public ActionResult manage_pending_projects()
        {

            return View(db.projects.Where(u => u.assigend_state_id == 3 && u.posting_state_id == 1).ToList());
            
        }

        public ActionResult projectapprove(int id)
        {
            project result = (from p in db.projects
                           where p.Id == id
                           select p).SingleOrDefault();

            result.posting_state_id = 2;

            db.SaveChanges();

            return RedirectToAction("manage_pending_projects");
        }

        public ActionResult projectdelete(int id)
        {
            project p = db.projects.Find(id);
            db.projects.Remove(p);
            db.SaveChanges();
            return RedirectToAction("manage_pending_projects");
        }
        public ActionResult projecthomedelete(int id)
        {
            project p = db.projects.Find(id);
            db.projects.Remove(p);
            db.SaveChanges();
            return RedirectToAction("manage_home_page");
        }

        public ActionResult manage_home_page()
        {
            return View(db.projects.Where(u => u.assigend_state_id == 3 && u.posting_state_id == 2).ToList());
        }

        [HttpPost]
       public ActionResult update_home_project(int id)
        {
            project result = (from p in db.projects
                              where p.Id == id
                              select p).SingleOrDefault();

                       db.SaveChanges();

            return RedirectToAction("manage_pending_projects");
        }



        public ActionResult Projectdetails(int? id)
        {
            if (id == null)
 
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                
            }
            else
                return View(db.projects.Find(id));
            
        }
        public ActionResult Statistical()
        {
            return View();
        }
    }
}

IA/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;


namespace Test.Controllers
{
	public class CustomerController : Controller
	{
        Database2Entities3 db = new Database2Entities3();

		//
		// GET: /Customer/
		public ActionResult Index()
		{
			return View();
		}



		public ActionResult CreateProject()
		{
			return View();
		}

        


		[HttpPost]
		public ActionResult CreateProject(project project)
		{

			project.assigend_state_id = 3;
			project.posting_state_id = 1;
            int id = Convert.ToInt32(Session["ID"]);
            project.customer_id = id;
            project.creation_date = DateTime.Now;
			db.projects.Add(project);
		

			db.SaveChanges();
			return  RedirectToAction("GetProjects");
		}
		public ActionResult GetProjects()
		{
            int id = Convert.ToInt32(Session["ID"]);
            return View(db.projects.Where(u =>  u.customer_id == id).ToList());
		}

		public ActionResult Edit(int? id)
		{

			return View(db.projects.Find(id));
		}
		[HttpPost]
		public ActionResult Edit(project project)
		{
			project result = (from p in db.projects
							 where p.Id == project.Id
							 select p).SingleOrDefault();
			result.description=project.description;
			result.duration=project.duration;
			result.title=project.title;

			db.SaveChanges();
			return RedirectToAction("GetProjects");
		}


		public ActionResult Remove(int ?id)
		{

			project project = db.projects.Find(id);

			if (project.assigend_state_id == 4)
			{
				return Content("Error !!, its already assigned to user !!");
			}
			else
			{
			
		   

				db.projects.Remove(project);
				db.SaveChanges();
				return RedirectToAction("GetProjects");

			}

			

		}



        public ActionResult Details(int? id)
        {

            return View(db.projects.Find(id));
        }

        public ActionResult get_projectmanger_request()
        {
            int id = Convert.ToInt32(Session["ID"]); 
            return View(db.requests.Where(u => u.reciever_id== id&& u.state_id==1).ToList());
        }

        public ActionResult Assign_pm(int id)
        {
            request result = (from p in db.requests
                              where p.Id == id
                              select p).SingleOrDefault();
            result.state_id = 4;
            mangaed_projects mp = new mangaed_projects();
            mp.pm_id = result.sender_id;
            mp.project_id = result.project_id;
            mp.state_id = 6;
            mp.start_date = DateTime.Now;
            mp.deliver_date = DateTime.Now;
            mp.cost = 5000;
            db.mangaed_projects.Add(mp);
            db.SaveChanges();
            return RedirectToAction("get_projectmanger_request");
        }
	}
}

IA/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;


namespace IA.Controllers
{
    public class HomeController : Controller
    {
        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /Home/
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult projects()
        {
            return PartialView("projects",db.projects.ToList());
        }

        [HttpPost]
        public JsonResult List()
        {
            var states = db.user_type.Where(c => c.id != 1).ToList();
            List<SelectListItem> listates = new List<SelectListItem>();

            listates.Add(new SelectListItem { Text = "Select Type", Value = "0" });
            if (states != null)
            {
                foreach (var x in states)
                {
                    listates.Add(new SelectListItem { Text = x.name, Value = x.id.ToString() });

                }



            }


            return this.Json(new SelectList(listates, "Value", "Text", JsonRequestBehavior.AllowGet));
        }  
        
	}
}

IA/Controllers/PMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;

namespace Test.Controllers
{
    public class PMController : Controller
    {

        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /PM/
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult getCutomerProjects()
        {
           
            //return Content("user"+x);
            return View(db.projects.Where(u => u.assigend_state_id == 3 && u.posting_state_id == 2).ToList());
        }

        public ActionResult getPmProjects()
        {
              int pm_id = Convert.ToInt32(Session["ID"]);
            List<project> list = new List<project>();

            var projects = db.mangaed_projects.Where(s => s.pm_id == pm_id);
            if(projects.Count() !=0)
            {
                foreach(var x in projects)
                {
                    list.Add(db.projects.Find(x.project_id));
                }
            }
            return View(list);

        }

        public ActionResult Details(int? id)
        {
            //var x = Session["ID"];
            //return Content("user"+x);
            return View(db.projects.Find(id));
        }

        public ActionResult Manage(int? id)
        {
            Session["project_id"] =id;

            return View();
        }

        [HttpPost]
        public ActionResult Manage(mangaed_projects ma)
        {

            int project_id = Convert.ToInt32(Session["project_id"]);
            int pm_id = Convert.ToInt32(Session["ID"]);

            ma.project_id =project_id;
            ma.pm_id = pm_id;
            ma.state_id = 6;// om progress
            

          
            db.mangaed_projects.Add(ma);


            db.SaveChanges();
            return RedirectToAction("getCutomerProjects");
        }

        public ActionResult getTeamLeaders()
        {

            return View(db.users.Where(u => u.type_id == 5).ToList());
        }


        public ActionResult getJuniorEngineers()
        {
            //junior engineer
            return View(db.users.Where(u => u.type_id == 3).ToList());
        }
        public ActionResult SendRequestToTeamLeader(int? id)
        {
            Session["leaderId"] = id;
 

            return View();
        }

        [HttpPost]
        public ActionResult SendRequestToTeamLeader(request req)
        {
          
           int pm_id = Convert.ToInt32(Session["ID"]);
           int tl_id = Convert.ToInt32(Session["leaderId"]);

           req.state_id = 1;
           req.sender_id = pm_id;
           req.reciever_id =tl_id;
      
            db.requests.Add(req);
            db.SaveChanges();

      
            return RedirectToAction("getPmProjects");
        }
        //SendRequestToJuniorEngineer


        public ActionResult SendRequestToJuniorEngineer(int? id)
        {
            Session["developerId"] = id;


            return View();
        }

        [HttpPost]
        public ActionResult SendRequestToJuniorEngineer(request req)
        {

            int pm_id = Convert.ToInt32(Session["ID"]);
            int tl_id = Convert.ToInt32(Session["developerId"]);
            req.state_id = 1;
            req.sender_id = pm_id;
            req.reciever_id = tl_id;

            db.requests.Add(req);
            db.SaveChanges();


            return RedirectToAction("getPmProjects");
        }


        public ActionResult deliverProject(int? id)
        {

            mangaed_projects result = (from p in db.mangaed_projects
                              where p.project_id == id
                              select p).FirstOrDefault();


            int result_com = DateTime.Compare(result.deliver_date, DateTime.Now);
            

            if (result_com < 0){
                result.deliver_date = DateTime.Now;
                result.state_id = 7;
                db.SaveChanges();
                
        }
            
            else{
                return Content("Error");

             }
            
          
           
           return RedirectToAction("getPmProjects");
           
        }


        public ActionResult getDeliveredProjects()
        {

            int pm_id = Convert.ToInt32(Session["ID"]);
            List<project> list = new List<project>();

            var projects = db.mangaed_projects.Where(s => s.pm_id == pm_id && s.state_id==7);
            if (projects.Count() != 0)
            {
                foreach (var x in projects)
                {
                    list.Add(db.projects.Find(x.project_id));
                }
            }
            return View(list);
        }

        public ActionResult getProjectmembers(int? id)
        {

            List<user> list = new List<user>();

            var project_members = db.project_members.Where(s => s.project_id == id);
            if (project_members.Count() != 0)
            {
                foreach (var x in project_members)
                {
                    list.Add(db.users.Find(x.member_id));
                }
            }
            return View(list);
        }


        public ActionResult DeleteMember(int ?id)
        {

            project_members result = (from p in db.project_members
                              where p.member_id == id
                              select p).SingleOrDefault();


            db.project_members.Remove(db.project_members.Find(result.Id));
            db.SaveChanges();
            return RedirectToAction("getProjectmembers");
        }

        public ActionResult DeleteProject(int? id)
        {


            mangaed_projects result = (from p in db.mangaed_projects
                                      where p.project_id == id
                                      select p).FirstOrDefault();
            Session["myid"] = result.Id;
            project po = (from p in db.projects
                          where p.Id == result.project_id
                          select p).SingleOrDefault();
            po.assigend_state_id = 3;

            db.mangaed_projects.Remove(db.mangaed_projects.Find(result.Id));

            db.SaveChanges();



            return RedirectToAction("getPmProjects");
        }

	}
}

/*
 
            int result_com = DateTime.Compare(result.deliver_date, DateTime.Now);
            string relationship;

            if (result_com < 0)
                relationship = "is earlier than";
            else if (result_com == 0)
                relationship = "is the same time as";
            else
                relationship = "is later than";*/

IA/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IA.Models;

namespace IA.Controllers
{
    public class UserController : Controller
    {
        Database2Entities3 db = new Database2Entities3();
        //
        // GET: /User/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index2()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult login(user user)
        {
            user myUser = db.users.FirstOrDefault(u => u.email.Equals(user.email) && u.password.Equals(user.password));

            if (myUser != null)
            {
                //TempData["ID"] = myUser.id;
                Session["ID"] = myUser.id;
                Session["phone"] = myUser.phone_number;
                Session["name"] = myUser.fname + " " + myUser.lname;
                Session["usertype"] = myUser.type_id;
                Session["email"] = myUser.email;
                //Session["jobdesc"] = myUser.user_type.name;
                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewBag.message = "User name or password is not Valid";
                return RedirectToAction("Index", "Home");
            }
 
        }

        public ActionResult logout()
        {
            Session.Abandon();//DESTROY SESSION
            return RedirectToAction("index","Home");
        }


        public ActionResult register()
        {
            return View();
        }



        [HttpPost]
        public ActionResult register(user u)
        {
            if(u!=null)
            {
                Session["ID"] = u.id;
                Session["name"] = u.fname + " " + u.lname;
                Session["usertype"] = u.user_type;
                Session["email"] = u.email;
                db.users.Add(u);
                db.SaveChanges();
                login(u);
                return RedirectToAction("index","Home");
            }
            else
            {
                ViewBag.message = "please fill all filds";
                return View();
            }
            
        }
        
	}



}

IA/Views/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Real Estate</title>
    <link href="~/Scripts/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Scripts/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/Site.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <header>
        <div class="header-upper">
            <div class="container">
                <ul class="col-lg-9 col-md-8 col-sm-6 col-xs-12">
                    <li>
                        <a href="#"><i aria-hidden="true" class="fa fa-globe"></i> Email :info@realState.com</a>
                    </li>
                </ul>
                <ul class=" col-lg-3 col-md-4 col-sm-6 col-xs-12"> 
@if (HttpContext.Current.Session["ID"] == null)
{ 
                    <li>
                        <a href="#"><i aria-hidden="true" class="fa fa-registered"></i> Register</a>
                    </li>
                    <li>
                        <a href="#"><i aria-hidden="true" class="fa fa-sign-in"></i> Login</a>
                    </li>
}
                </ul>
            </div>
        </div>
        <div class="header-lower nav-justified">
            <div class="container">
                <div class="logo">
                    <a href="index.html"><img alt="image" src="~/image/logo.png"></a>
                </div>
                <div class="hire">
                    <div class="box address">
                        <i aria-hidden="true" class="fa fa-home"></i>
                        <ul>
                            <li><strong>address :</strong></li>
                            <li>100A Birmingham, United States.</li>
                        </ul>
                    </div>
                    <div class="box phone">
                        <i aria-hidden="true" class="fa fa-phone"></i>
                        <ul>
                            <li><strong>phone :</strong></li>
                            <li>01145602349</li>
                        </ul>
                    </div>
                    <div class="box btn">
                        <a href="#">hire an agent</a>
                    </div>
                </div>
            </div>
        </div>
    </header>

   

    <section class="container-fluid">
        <div class="row">
            <section class="left-fun col-md-10">
                <div class="details">
                    <div class="container">
                        <h2>Personal Information</h2>
                        <div class="image col-md-3"><img alt="" src="~/image/anonymous%20(1).png"></div>
                        <div>
                            <ul>
                                <li><span>Name : @HttpContext.Current.Session["Name"] </span></li>
                                <li><span>Mobile : @HttpContext.Current.Session["phone"]</span></li>
                                <li><span>Email : @HttpContext.Current.Session["email"]</span> </li>
                                <li><span>Job Description: @HttpContext.Current.Session["jobdesc"]</span></li>
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="request">
                    <div class="container">
                        <div class="row">
                            @RenderBody()
                        </div>
                    </div>
                </div>

            </section>
            <section class="right-navs col-md-2">
                <nav>
                    <ul>
                        <li>
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        
                        @if (HttpContext.Current.Session["ID"] != null)
                        {
                            if (Convert.ToInt32(HttpContext.Current.Session["usertype"]) == 1)
                            {
                        <li>
                            @Html.ActionLink("Manage Home", "manage_home_page", "Admin")

                        </li>
                        <li>

                            @Html.ActionLink("Pending Posts", "manage_pending_projects", "Admin")
                        </li>
                        <li>

                            @Html.ActionLink("Users", "manageusers", "Admin")
                        </li>
                            }
                            else if (Convert.ToInt32(HttpContext.Current.Session["usertype"]) == 5)
                            {
                                <li>
                                    @Html.ActionLink("Project requests", "Index", "TeamLeader")
                                </li>
                            
                            
                                <li>

                                    @Html.ActionLink("Managed Project", "currentProjects", "TeamLeader")
                                </li>
                            }
                            else if (Convert.ToInt32(HttpContext.Current.Session["usertype"]) == 2)
                            {
                                <li>
                                    @Html.ActionLink("Managed Projects", "getPmProjects", "PM")
                                </li>
                                <li>
                                    @Html.ActionLink("Deliverd Projects", "getDeliveredProjects", "PM")
                                </li>
                                <li>
                                    @Html.ActionLink("Projects", "getCutomerProjects", "PM")
                                </li>
                            }

                            <li>
                         @Html.ActionLink("Logout", "logout", "User")
                            </li>
                        }

                    </ul>
                </nav>
            </section>
        </div>
    </section>
    <!-- about -->
    <section class="about" id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="about-us">
                        <h2>About Us</h2>
                        <div class="txt">
                            <span>They really are a scream the addams am making your way in the world they really are a scream the miss ad dams they are a really are a scream the addams cream the miss ad dams.</span>
                            <h2 class="phone">01145602349</h2><img src="~/image/logo.png">
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                    <div class="recent">
                        <h2>Recent Projects</h2>
                        <ul class="list-unstyled list">
                            <li>
                                <img src="~/image/1_009.png" class="img-circle" style="height:80px;width:80px" /><span>New Village</span>
                            </li>

                            <li>
                                <img src="~/image/2_009.png" class="img-circle" style="height:80px;width:80px" /><span>Home Town</span>
                            </li>
                            <li>
                                <img src="~/image/3_004.png" class="img-circle" style="height:80px;width:80px" /><span>New Market</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4">
                    <div class="site-map">
                        <h2>Contact us</h2>
                        <ul class="list-unstyled list">
                            <li>
                                <i aria-hidden="true" class="fa fa-facebook"></i> <a href="https://www.facebook.com/">Facebook</a>
                            </li>
                            <li>
                                <i aria-hidden="true" class="fa fa-twitter"></i> <a href="https://twitter.com">Twitter</a>
                            </li>
                            <li>
                                <i aria-hidden="true" class="fa fa-google-plus"></i> <a href="https://plus.google.com/">Google+</a>
                            </li>
                            <li>
                                <i aria-hidden="true" class="fa fa-linkedin"></i> <a href="https://www.linkedin.com">LinkedIn</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer>
        <span>&copy; Copyrights @DateTime.Now.Year  Projects Management System for Constructions and Real Estate. All Rights Reserved</span>
    </footer>



    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.nicescroll.min.js"></script>
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/respond.min.js"></script>
    <script src="~/Scripts/mixitup.min.js"></script>

    <script>
        new WOW().init();
    </script>
    <script src="~/Scripts/script.js"></script>

</body>
</html>